AWSTemplateFormatVersion: "2010-09-09"
Description: Lacework AWS Config Security Audit Integration

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Parameters:
          - ResourceNamePrefix
          - ExternalID
          - MainAccountSNS
    ParameterLabels:
      ResourceNamePrefix:
        default: Resource name prefix
      ExternalID:
        default: ExternalID
      MainAccountSNS:
        default: SNS Topic in main account

Parameters:
  ResourceNamePrefix:
    Default: lw-prefix
    Description: Names of resources created by the stack will be prefixed with this value to ensure uniqueness.
    Type: String
    MinLength: "1"
    MaxLength: "45"
    AllowedPattern: ^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$
    ConstraintDescription: Invalid resource name prefix.  Must match pattern ^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$
  ExternalID:
    Description: The cross-account access role created by the stack will use this value for its ExternalID.
    Type: String
    MinLength: "2"
    MaxLength: "1224"
    ConstraintDescription: Invalid ExternalID value.  Must be between 2 and 1224 characters
  MainAccountSNS:
    Description: ARN of SNS topic that we post to start the integration
    Type: String

Resources:
  LaceworkCrossAccountAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Join:
          - '-'
          - - Ref: ResourceNamePrefix
            - laceworkcwsrole-sa
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS: ["arn:aws:iam::434813966438:role/lacework-platform"]
            Condition:
              StringEquals:
                sts:ExternalId:
                  Ref: ExternalID
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit

  LaceworkCWSPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: LaceworkCWSPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: GetEc2DefaultEncryption
            Action:
              - ec2:GetEbsEncryptionByDefault
            Effect: Allow
            Resource: '*'
          - Sid: GetBucketPublicAccessBlock
            Action:
              - s3:GetBucketPublicAccessBlock
            Effect: Allow
            Resource: '*'
      Roles:
        - Ref: LaceworkCrossAccountAccessRole

  LaceworkSnsCustomResource:
    Type: Custom::LaceworkSnsCustomResource
    DependsOn:
      - LaceworkCWSPolicy
      - LaceworkCrossAccountAccessRole
    Properties:
      Type: AWS_CFG
      ServiceToken: !Ref MainAccountSNS
      RoleArn:
        Fn::GetAtt:
          - LaceworkCrossAccountAccessRole
          - Arn
      ExternalId:
        Ref: ExternalID
      AccountId:
        Ref: AWS::AccountId

Outputs:
  ExternalID:
    Description: External ID to share with Lacework AWS Config Security Audit
    Value:
      Ref: ExternalID
  RoleARN:
    Description: Cross account Role ARN for Lacework AWS Config Security Audit
    Value:
      Fn::GetAtt:
        - LaceworkCrossAccountAccessRole
        - Arn
  TemplateVersion:
    Description: Template version
    Value: "1.0"
